spring:
  application:
    name: jobbotdari-user
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8071"
#    import: optional:configserver:http://config-server:8071
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh