spring:
  application:
    name: jobbotdari
  config:
    import: "optional:configserver:http://localhost:8071"
#    import: "optional:configserver:http://config-server:8071"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh